# *****************************************************
# Variables to control Makefile operation
 
CC = g++
CFLAGS = -Wall -g -std=c++17

# ****************************************************
# Targets needed to bring the executable up to date

test1: 
	$(CC) $(CFLAGS) -o test1 int2type.cpp

test2: 
	$(CC) $(CFLAGS) -o test2 constexper_if.cpp

test3: 
	$(CC) $(CFLAGS) -o test3 compiler_error.cpp

test4: 
	$(CC) $(CFLAGS) -o test4 is_base_of.cpp

clean:
	rm -f test*