# *****************************************************
# Variables to control Makefile operation
 
CC = g++
CFLAGS = -Wall -g

# ****************************************************
# Targets needed to bring the executable up to date

test1: main.cpp 
	$(CC) $(CFLAGS) -o test1 main.cpp

clean:
	rm -rf test*